### ISSUE TITLE
No TEs found

### ISSUE THREAD

**Issue by lanasushko** [kavonrtep/dante_ltr#7]
Hi!

Thanks for developing dante_ltr. I tried to run dante and dante_ltr on a genome but received an error message during the dante_ltr step.

I ran dante and dante_ltr with the following commands:
```
dante -q $genome -o $name'.dante.gff3' -c 10
dante_ltr -g $name'.dante.gff3' -s $genome -o $name'dante_ltr.annot' -M 1
```

Dante seemed to work find but dante_ltr showed this error message.

```
running analysis on whole input
reading gff...done
reading fasta...done
No complete TE found
No TEs found.
[1] TRUE
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'X' in selecting a method for function 'sapply': first argument must be a vector
Calls: sapply ... split -> split -> split.default -> .handleSimpleError -> h
Execution halted
```

Does this mean that there are actually no LTR-RTs in this genome? Or is it related to something else?

Thanks!

**Comment by kavonrtep** [comment]
Hi, can you upload the genome to github so I can check if it is not bug. Thanks
Petr

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: lanasushko ***@***.***>
Sent: Thursday, June 13, 2024 11:56:18 AM
To: kavonrtep/dante_ltr ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kavonrtep/dante_ltr] No TEs found (Issue #7)


Hi!

Thanks for developing dante_ltr. I tried to run dante and dante_ltr on a genome but received an error message during the dante_ltr step.

I ran dante and dante_ltr with the following commands:

dante -q $genome -o $name'.dante.gff3' -c 10
dante_ltr -g $name'.dante.gff3' -s $genome -o $name'dante_ltr.annot' -M 1


Dante seemed to work find but dante_ltr showed this error message.

running analysis on whole input
reading gff...done
reading fasta...done
No complete TE found
No TEs found.
[1] TRUE
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'X' in selecting a method for function 'sapply': first argument must be a vector
Calls: sapply ... split -> split -> split.default -> .handleSimpleError -> h
Execution halted


Does this mean that there are actually no LTR-RTs in this genome? Or is it related to something else?

Thanks!

**Comment by lanasushko** [comment]
Hi Petr

I used a Saccharomyces cerevisiae assembly from NCBI: https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_000146045.2/

I know that dante is designed mainly for plants but since it identified domains in this species I thought that maybe the full-length transposons could also be retrieved. The pipeline worked for the test genome and an Arabidopsis thaliana assembly.

Let me know! Thanks

**Comment by kavonrtep** [comment]
dante_ltr is designed for plants LTR-Rt but it is possible to run it on yeast with little hack. 
you have to modify te_constrain file to include additionaly LTR-RT category (Ty1-outgroup) - see the attachment below
then run dante_ltr as:
```bash
dante_ltr -g DANTE_full_output.gff3 -M 1 -o dante_ltr --te_constrains lineage_domain_order.csv -s GCF_000146045.2_R64_genomic.fna  -c 5
```
it will fail to generate graphical report but annotation of LTR-RT in GFF will be generated.

te_constrain file:
[lineage_domain_order.csv](https://github.com/user-attachments/files/15835045/lineage_domain_order.csv)

**Comment by lanasushko** [comment]
Thanks!
